# Generated by Django 3.2.4 on 2021-10-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurantaddexcel_restaurant_excel'),
        ('restaurant', '0010_merge_20211018_0713'),
    ]

    operations = [
    ]
